// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: waveshare

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Spinner1 = NULL;
lv_obj_t * ui_wifi = NULL;
lv_obj_t * ui_SDcard = NULL;
lv_obj_t * ui_sdbar = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_ssidlabel = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_Image3 = NULL;
lv_obj_t * ui_userlabel = NULL;
lv_obj_t * ui_MediaGen = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Spinner1 = lv_spinner_create(ui_Screen1, 1000, 90);
    lv_obj_set_width(ui_Spinner1, 146);
    lv_obj_set_height(ui_Spinner1, 155);
    lv_obj_set_x(ui_Spinner1, 0);
    lv_obj_set_y(ui_Spinner1, 24);
    lv_obj_set_align(ui_Spinner1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner1, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_wifi = lv_switch_create(ui_Screen1);
    lv_obj_set_width(ui_wifi, 50);
    lv_obj_set_height(ui_wifi, 25);
    lv_obj_set_x(ui_wifi, -48);
    lv_obj_set_y(ui_wifi, 132);
    lv_obj_set_align(ui_wifi, LV_ALIGN_CENTER);

    ui_SDcard = lv_switch_create(ui_Screen1);
    lv_obj_set_width(ui_SDcard, 50);
    lv_obj_set_height(ui_SDcard, 25);
    lv_obj_set_x(ui_SDcard, 49);
    lv_obj_set_y(ui_SDcard, 133);
    lv_obj_set_align(ui_SDcard, LV_ALIGN_CENTER);

    ui_sdbar = lv_bar_create(ui_Screen1);
    lv_bar_set_value(ui_sdbar, 10, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_sdbar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_sdbar, 159);
    lv_obj_set_height(ui_sdbar, 20);
    lv_obj_set_x(ui_sdbar, -1);
    lv_obj_set_y(ui_sdbar, -142);
    lv_obj_set_align(ui_sdbar, LV_ALIGN_CENTER);

    ui_Label1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 1);
    lv_obj_set_y(ui_Label1, -66);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Connected Users:");
    lv_obj_set_style_text_font(ui_Label1, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 0);
    lv_obj_set_y(ui_Label2, -117);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Connect to:");
    lv_obj_set_style_text_font(ui_Label2, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel1, 121);
    lv_obj_set_height(ui_Panel1, 27);
    lv_obj_set_x(ui_Panel1, 0);
    lv_obj_set_y(ui_Panel1, -92);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x223E87), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ssidlabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_ssidlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ssidlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ssidlabel, -2);
    lv_obj_set_y(ui_ssidlabel, -91);
    lv_obj_set_align(ui_ssidlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ssidlabel, " Jcorp_Nomad");
    lv_obj_set_style_text_color(ui_ssidlabel, lv_color_hex(0xA5E0F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ssidlabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ssidlabel, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image1, &ui_img_1472434861);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 35
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 35
    lv_obj_set_x(ui_Image1, 49);
    lv_obj_set_y(ui_Image1, 101);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image2 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image2, &ui_img_512784668);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 35
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 35
    lv_obj_set_x(ui_Image2, -48);
    lv_obj_set_y(ui_Image2, 101);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image3 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image3, &ui_img_1859342711);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 83
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 110
    lv_obj_set_x(ui_Image3, 0);
    lv_obj_set_y(ui_Image3, 20);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_userlabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_userlabel, 26);
    lv_obj_set_height(ui_userlabel, 41);
    lv_obj_set_x(ui_userlabel, -1);
    lv_obj_set_y(ui_userlabel, 14);
    lv_obj_set_align(ui_userlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_userlabel, "0");
    lv_obj_set_style_text_font(ui_userlabel, &ui_font_Font2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MediaGen = lv_textarea_create(ui_Screen1);
    lv_obj_set_width(ui_MediaGen, 170);
    lv_obj_set_height(ui_MediaGen, 315);
    lv_obj_set_align(ui_MediaGen, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_MediaGen, "Starting....");
    lv_obj_add_flag(ui_MediaGen, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_MediaGen, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Spinner1 = NULL;
    ui_wifi = NULL;
    ui_SDcard = NULL;
    ui_sdbar = NULL;
    ui_Label1 = NULL;
    ui_Label2 = NULL;
    ui_Panel1 = NULL;
    ui_ssidlabel = NULL;
    ui_Image1 = NULL;
    ui_Image2 = NULL;
    ui_Image3 = NULL;
    ui_userlabel = NULL;
    ui_MediaGen = NULL;

}
